# Generated by Django 3.2.9 on 2022-05-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
