# Generated by Django 3.2.9 on 2022-03-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='responders',
            field=models.ManyToManyField(blank=True, related_name='responded_resumes', to='job_site.Employer'),
        ),
        migrations.AddField(
            model_name='resume',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responders',
            field=models.ManyToManyField(blank=True, related_name='responded_vacancies', to='job_site.Employee'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='job_site.Tag'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='vacancies', to='job_site.Tag'),
        ),
    ]
