# Generated by Django 3.2.9 on 2022-05-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_site', '0002_auto_20220501_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
