# Generated by Django 3.2.9 on 2022-05-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_site', '0003_auto_20220507_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='code',
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
