# Generated by Django 3.2.9 on 2022-03-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_site', '0003_auto_20220321_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='body',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='duties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
