# Generated by Django 3.2.9 on 2022-05-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_site', '0004_auto_20220509_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
