# Generated by Django 3.2.9 on 2022-04-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_site', '0005_auto_20220329_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='draft',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='closed',
            new_name='is_published',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='body',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='responders',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='responders',
        ),
        migrations.AddField(
            model_name='employee',
            name='favorite_vacancies',
            field=models.ManyToManyField(blank=True, related_name='employees_who_like', to='job_site.Vacancy'),
        ),
        migrations.AddField(
            model_name='employer',
            name='favorite_resumes',
            field=models.ManyToManyField(blank=True, related_name='employers_who_liked', to='job_site.Resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ready_distant_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='ready_relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experiance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='job_site.employee'),
        ),
    ]
