# Generated by Django 3.2.9 on 2022-05-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_site', '0005_employer_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
