# Generated by Django 3.2.9 on 2022-05-13 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_site', '0006_employer_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy2Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('declined', models.BooleanField(blank=True, null=True)),
                ('employee_message', models.TextField(blank=True, null=True)),
                ('from_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_to_resumes', to='job_site.vacancy')),
                ('to_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_from_vacancies', to='job_site.resume')),
            ],
            options={
                'verbose_name': 'Vacancy to Resume',
                'verbose_name_plural': 'Vacancies to Resumes',
            },
        ),
        migrations.CreateModel(
            name='Resume2Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('declined', models.BooleanField(blank=True, null=True)),
                ('employer_message', models.TextField(blank=True, null=True)),
                ('from_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_to_vacancies', to='job_site.resume')),
                ('to_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_from_resumes', to='job_site.vacancy')),
            ],
            options={
                'verbose_name': 'Resume to Vacancy',
                'verbose_name_plural': 'Resumes to Vacancies',
            },
        ),
    ]
