# Generated by Django 3.2.9 on 2022-04-15 20:26

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job_site', '0007_alter_employee_favorite_vacancies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True, null=True)),
                ('salary', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('views', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='job_site.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='job_site.client')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='job_site.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True, null=True)),
                ('salary', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('views', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='job_site.category')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='job_site.freelancer')),
                ('tags', models.ManyToManyField(blank=True, related_name='services', to='job_site.Tag')),
            ],
        ),
    ]
