# Generated by Django 3.2.9 on 2022-05-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_site', '0007_resume2vacancy_vacancy2resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume2vacancy',
            name='declined',
        ),
        migrations.AddField(
            model_name='resume2vacancy',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
