# Generated by Django 3.2.9 on 2022-04-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_site', '0008_service_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='favorite_services',
            field=models.ManyToManyField(blank=True, related_name='clients_who_liked', to='job_site.Service'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='favorite_tasks',
            field=models.ManyToManyField(blank=True, related_name='freelancers_who_liked', to='job_site.Task'),
        ),
    ]
