# Generated by Django 3.2.9 on 2022-05-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_site', '0008_auto_20220513_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy2resume',
            name='declined',
        ),
        migrations.AddField(
            model_name='resume2vacancy',
            name='type',
            field=models.CharField(default='Отклик на вакансию', max_length=50),
        ),
        migrations.AddField(
            model_name='vacancy2resume',
            name='type',
            field=models.CharField(default='Приглашение на работу', max_length=50),
        ),
        migrations.AddField(
            model_name='vacancy2resume',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
