# Generated by Django 3.2.9 on 2022-06-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_site', '0013_auto_20220526_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='by_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
