# Generated by Django 3.2.9 on 2022-05-12 03:59

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='as_client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='as_employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='as_employer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='as_freelancer',
        ),
        migrations.AddField(
            model_name='user',
            name='reg_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
